### ISSUE TITLE
Code-review: Low-level fixes

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#156]
Diff: <https://github.com/hammerlab/ketrew/compare/2c76bd4...639efec>

This chunk does various fixes:

- Rewrite & improve daemonization function
  (This time we use a double fork like
  [here](http://stackoverflow.com/questions/3095566/linux-daemonize)).
- Fix stack-overflow due to debug statement
  (Using `s` on very big strings seems to trigger a Stack-overflow:
    [docout#1](https://bitbucket.org/smondet/docout/issue/1/the-s-combinartor-can-stack-overflow))
- Make server check status before starting (fixes issue
  [`hammerlab/ketrew#131`](https://github.com/hammerlab/ketrew/issues/131)).

**Comment by rleonid** [comment]
Why are you clearing the `exit_hooks` here
```OCaml
let exit_parent () =
  Lwt_sequence.iter_node_l Lwt_sequence.remove Lwt_main.exit_hooks;
  exit 0
in
```
I can't find any cases where you set `Lwt.at_exit`. There is 
```OCaml
let init () =
  if not !initialized then (
    let open Unix in
    let term_init = tcgetattr stdin in
    at_exit (fun () -> tcsetattr stdin TCSADRAIN term_init);
    initialized := true;
    ()
  )
```
at https://github.com/hammerlab/ketrew/blob/master/src/lib/ketrew_interaction.ml#L27, but isn't that registering an exit with `Unix`. Are the two calls compatible? 

--------------------

I would reverse the order of the match logic here https://github.com/hammerlab/ketrew/compare/2c76bd4...639efec#diff-8979eac4e90d62b385182fd2ae18ead5R312, ie. 
```OCaml
let pid = Unix.fork () in
if pid <> 0 then
  parent_stuff ()
else
  child_stuff ()
```
since `child_stuff` is so much longer.

---------------

https://github.com/hammerlab/ketrew/compare/2c76bd4...639efec#diff-8979eac4e90d62b385182fd2ae18ead5R334
Any particular reason why `Unix.chdir` is commented out?

---------------

I always find this form of writing redirects
```Bash
cat << EOBLOB > $test_authorized_tokens
```

magical, since I start wondering why you're starting a file with `$test_authorized_tokens`. In this case it's not so bad, since `$` indicates a variable. But I do find

```Bash
cat > $test_authorized_tokens << EOBLOB 
```
easier to grok immediately. I'll get used to it if you like the other style.

**Comment by smondet** [comment]
> Why are you clearing the `exit_hooks` here
> ```OCaml
> let exit_parent () =
>   Lwt_sequence.iter_node_l Lwt_sequence.remove Lwt_main.exit_hooks;
>   exit 0
> in
> ```

Maybe some library (or module within `lwt.unix`) is adding hooks; I just copied
that line from
[`lwt_daemon.ml`](https://github.com/ocsigen/lwt/blob/master/src/unix/lwt_daemon.ml#L60)

> --------------------
> 
> I would reverse the order of the match logic here https://github.com/hammerlab/ketrew/compare/2c76bd4...639efec#diff-8979eac4e90d62b385182fd2ae18ead5R312, ie. 
> ```OCaml
> let pid = Unix.fork () in
> if pid <> 0 then
>   parent_stuff ()
> else
>   child_stuff ()
> ```
> since `child_stuff` is so much longer.

ok but will still use `match .. with` :)

> 
> ---------------
> 
> https://github.com/hammerlab/ketrew/compare/2c76bd4...639efec#diff-8979eac4e90d62b385182fd2ae18ead5R334
> Any particular reason why `Unix.chdir` is commented out?

It's recommended here:
http://stackoverflow.com/questions/3095566/linux-daemonize

but so far I prefered being able to use relative paths, maybe should force
absolute paths → https://github.com/hammerlab/ketrew/issues/165

> 
> ---------------
> 
> I always find this form of writing redirects
> ```Bash
> cat << EOBLOB > $test_authorized_tokens
> ```
> 
> magical, since I start wondering why you're starting a file with `$test_authorized_tokens`. In this case it's not so bad, since `$` indicates a variable. But I do find
> 
> ```Bash
> cat > $test_authorized_tokens << EOBLOB 
> ```
> easier to grok immediately. I'll get used to it if you like the other style.


Bash syntax has a lot of dark unreadable magic :)

Never paid attention to that one; I'm happy to change to the other order.

**Comment by rleonid** [comment]
I'd document the `lwt_daemon.ml` thing and great to everything else.
