### ISSUE TITLE
Code-review: Bunch of documentation fixes

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#167]
Diff: <https://github.com/hammerlab/ketrew/compare/f8c6bf9...051973c>

- Remove obsolete references to ATD (fixes #158)
- Update “Glossary” document (fixes #161)
- Fix long-running plugins documentation (fixes #162)
- Fix link in `The_HTTP_API.md` (#164)

**Comment by rleonid** [comment]
At https://github.com/hammerlab/ketrew/compare/f8c6bf9...051973c#diff-3b7a49d54ba3c3d9bcfb25f0a4f1f9aaR18
I'd mention what happens when no `playground` is specified.

https://github.com/hammerlab/ketrew/compare/f8c6bf9...051973c#diff-3b7a49d54ba3c3d9bcfb25f0a4f1f9aaR27
"that need to be satisfied or run before a target can start"

activable target -> ready target or waiting target . activable is super awkward, stupid English.
