### ISSUE TITLE
Code-review: Optimize storage for the engine

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#173]
Diff: <https://github.com/hammerlab/ketrew/compare/acce5b9...13619e3>

- 3d66e4d Create separate DB collection for finsihed targets</br>
It also stores the “pointers” which are immutable artifacts.
This contributes to #73 as it removes a lot of useless work in the `step`
function.
- 022ca26 Remove obsolete code in `Ketrew_engine`</br>
This is the “engine” part of #159.
- c78a7bd Remove obsolete function `add_stored_targets`</br>
- 13619e3 Put “passive” targets in a separate collection</br>

**Comment by rleonid** [comment]
I guess `passive_targets_collection` and the like at https://github.com/hammerlab/ketrew/compare/acce5b9...13619e3#diff-f3be9e7a53a8212c3f074d89c8da01e0R143 are strings because of the `Trakeva` interface for `collections`?

Maybe document this specifically, because I was confused why you used a string as opposed to an ADT.

Why not make `from` an optional argument that defaults to `[ passive_targets_collection; active_targets_collection; finished_targets_collection; ]` so that you don't have to overwrite here  https://github.com/hammerlab/ketrew/compare/acce5b9...13619e3#diff-f3be9e7a53a8212c3f074d89c8da01e0R294?

**Comment by smondet** [comment]
See above, I added some commenting and renamed the first `all_targets`.

I like `~from` being a mandatory argument for readability, with the renaming I hope it's not confusing any more.

I also pushed a global renaming of `current_targets` to `all_targets` which is partially related to this:
https://github.com/hammerlab/ketrew/commit/9214634c11ed5c2771f48f7a9883460e43d057c9

**Comment by rleonid** [comment]
Looks good.
