### ISSUE TITLE
Code-review: configuration clean-up and documentation

### ISSUE THREAD

**Issue by smondet** [hammerlab/ketrew#181]
Diff: <https://github.com/hammerlab/ketrew/compare/3ceba88...b782227>

This is all related to the configuration:

- Update the documentation: this includes the improvements described in
  [#163](https://github.com/hammerlab/ketrew/issues/163).
- Remove obsolete configuration value: `persistent_state_key`.

**Comment by smondet** [comment]
I've update the online build of the documentaiton:

- http://seb.mondet.org/software/ketrew/The_Configuration_File.html
- http://seb.mondet.org/software/ketrew/api/Ketrew_configuration.html

**Comment by rleonid** [comment]
https://github.com/hammerlab/ketrew/compare/3ceba88...b782227#diff-8406cf45dbbf9d60df318d41a35a9efbR123
`s/Details on the options/Option details/`

https://github.com/hammerlab/ketrew/compare/3ceba88...b782227#diff-ee608fcd6a97e9a95201b36c84dbd402R31
`s/contents of a given instance of a configuration/contents of a configuration/`

https://github.com/hammerlab/ketrew/compare/3ceba88...b782227#diff-ee608fcd6a97e9a95201b36c84dbd402R75
color -> with_color in doc

https://github.com/hammerlab/ketrew/compare/3ceba88...b782227#diff-ee608fcd6a97e9a95201b36c84dbd402R149
-> should return _an_ explicit error

The rest looks fine. This is an example of a code review that would have been much easier in a pull request. So that I could just edit directly or comment at specific points in the code.
