### ISSUE TITLE
IO Multiplexing

### ISSUE THREAD

**Issue by rizo** [hammerlab/ketrew#196]
Hi! Recently started playing with ketrew to manage the workflow of execution of the Analytics System within my company.

We've been using shell scripts to glue small OCaml binaries that process large amounts of data and pass the results through a pipeline.

Here is a simplified description of a usual workflow:

- Fetch the input data from the database to a CSV file on the filesystem.
- Compress the CSV file with `gzip`.
- Use `zcat` with multiple simultaneous redirects to the metrics processors (["Zsh's Mulitios"](http://zsh.sourceforge.net/Doc/Release/Redirection.html#Multios)).
- Write the results to the filesystem and the metrics database.
- Some metrics have dependencies on other metrics, so they use the previously calculated values (from the filesystem) as the input and finally write the results to the metrics database.

One interesting step here is the multiplexing of the output to multiple consumers with `zsh`. Here's an example of what I'm talking about:

```
{zcat /path/to/data.csv.gz} \
  > >(metrics_a param_1 param_2 >! /path/to/metric_a/output.csv) \
  > >(metrics_b param_1 param_2 >! /path/to/metric_b/output.csv) \
  > >(metrics_c param_1 param_2 >! /path/to/metric_c/output.csv) \
  > >(metrics_d param_1 param_2 >! /path/to/metric_d/output.csv)
```

Since the data file is large we try to avoid the need of piping it separately to each metric and pass the output of to multiple metrics at the same time.

Do you thing something similar could be achieved with ketrew? If so, how? If not, what would be the best way to extend ketrew to support this feature?

**Comment by smondet** [comment]
There is no I/O mutliplexing ni Ketrew, or at least for now we have no backend that supports that (because the backends we have are for running shell scripts on a cluster or indenpendent host, so I/O multiplexing would mean SSH connections between nodes of the cluster?)

Assuming most steps take at least a few seconds for Ketrew to be worth it, parallelizing that kind of workflow into a clean Ketrew workflow seems easy. (I.e. without `Multios`, it would be just dependent commands, but they could be happening on different processes or even hosts).
The advantage of separating everything is that the workflow is more restartable, and one can investigate when the analyses don't work.

Did you look at our big Ketrew pipelines?
see here for example:
https://github.com/hammerlab/biokepi/blob/master/src/lib/mutect.ml#L80
We split our `mutect` job into smaller jobs, they run in parallel, and then we assemble back the results (`vcfconcat`). To give a scale, this makes the whole analysis take about 1.5 hours instead of more than 24. 
(But this requires a shared filesystem for the targets to write to the same place of course)

Extending Ketrew for I/O Mutiplexing:
The module type of the backends is actually very general, so implementing a backend plugin that does that is not impossible (even as a user) but not obvious either :)
I don't know how the API would look like.
