### ISSUE TITLE
Query returning wrong results

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#393]
`(and (created-in-the-past (weeks 4.2)) (is-failed) (not (is-dependency-dead)))` returned at least one node that explicitly is "Dependencies_failed", or, "dependency dead".

**Comment by smondet** [comment]
Was it fully "Finsihed" or the status was red but with a different name still (there is an interval of time where something is dependency-dead and the `on_failure_activate` are being started and all?

because the function behind `is-dependency-dead` 
https://github.com/hammerlab/ketrew/blob/master/src/pure/target.ml#L724
actually means “is completely finished and dead because of dependencies”

**Comment by ihodes** [comment]
I'm closing this as I don't see it anymore after I upgraded Ketrew/restarted.

**Comment by ihodes** [comment]
This is still the case; @smondet's guess is correct. Easy fix, apparently.
