### ISSUE TITLE
Daemon is broken

### ISSUE THREAD

**Issue by ihodes** [hammerlab/ketrew#416]
Don't know how. @smondet and I spent an hour or so trying to debug it to no avail.

Need something more resilient (or to just not support it?)

**Comment by smondet** [comment]
Yes there is so much push against processes self-daemonizing that we may just remove the whole feature and tell users to use `screen` or whatever they have.

**Comment by hammer** [comment]
Which daemon are we talking about? @smondet what push against processes self-daemonizing? What is the preferred way for putting a process into a long-lived state?

**Comment by smondet** [comment]
@hammer He's talking about the server running as daemon (to be fair most of the time we lost on that is because we didn't read the date of a week-old log entry and thought it was the problem to solve).

The “push” I see is that every time we talk about daemons and their problems, people say “oh you should not daemonize and instead use `systemd` or equivalent” or “daemonizing is an anti-pattern”, etc.
E.g. https://github.com/mirleft/ocaml-tls/issues/302#issuecomment-151334698 
https://groups.google.com/forum/#!msg/ocaml-core/N8dUkus8URA/camkTl8ACAAJ

**Comment by hammer** [comment]
I guess http://0pointer.de/public/systemd-man/daemon.html#New-Style%20Daemons is the "new style" way to daemonize a process?

**Comment by smondet** [comment]
Exorcised by #480 :fire:
